{% set name = "redflag" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redflag-{{ version }}.tar.gz
  sha256: 11c452c0b44b9e1606cddda4ae4de9fae270a0531732d58d1fbc6d9d255e6f3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - scipy !=1.10.0
    - scikit-learn

test:
  imports:
    - redflag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://scienxlab.org/redflag/
  summary: Raise red flags on machine learning datasets.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwinkunks
